rabbitmq:
  host: "192.168.3.228"
  port: 5672
  username: "myuser"
  password: "mypassword"

nodes:
  "192.168.3.100":
    id: "node1"
    port: 7070
  "192.168.3.101":
    id: "node2"
    port: 7071
  "192.168.3.102":
    id: "node3"
    port: 7072 